language: python
python:
    - "2.7"
    - "3.4"
    - "3.6"
    - "3.7"
    - "pypy"
install:
    - pip install .
    - pip install -r tests/requirements.txt
    # - ./tests/setup.sh
script: nosetests -v --with-coverage --cover-package=project_generator
after_success: coveralls
sudo: false
